### ISSUE TITLE
Rules loaded twice on each tokenize() call

### ISSUE THREAD

**Issue by nljubesi** [clarinsi/obeliks#1]
I am just a messenger, so shoot me. @IgorTavcar has noticed in his analyses of the classla package that in the obeliks.rules.tokenize() method the function load_rules() is invoked twice for each tokenize() call. He suggests for the rules to be loaded and cached during the initialization phase of the processor.

He has also a very nice visualization at https://github.com/IgorTavcar/classla_lab#tokenization that shows ~80% of the processing time being used on rule loading.

**Comment by msinkec** [comment]
`load_rules()` is invoked twice because it is used to load two separate files. See https://github.com/clarinsi/obeliks/blob/fc4de4c8d0a3f3d0419bfa5a4b066ae1ede19fca/obeliks/rules.py#L168-L169.

Reusing already loaded rules is possible but it would require some modification of the module interface. So instead of calling `obeliks.run()` the user would first instatiate a processor object, which holds cached state and then call run on that. Furthermore, I could also put the rules in a single file to reduce system call overhead, if that would help performance wise.

What do you guys think? @IgorTavcar @nljubesi

**Comment by nljubesi** [comment]
I am very much in favour of loading rules once during the instantiation of the tokenizer, rather on each tokenize() call.

Not sure whether merging rules will help (if these are different rules, and all are needed), but given that 80% of the current tokenization time goes to rule loading, I would suggest you check that only necessary rules are loaded (once).

**Comment by msinkec** [comment]
I made the rules load at the module import time, so they should load only once per program execution now. I also pushed some text parsing bug fixes.

Commit: 84f28b4d730ba8ca9f17cfa2412bd201a5c670d5
New release 1.0.6: https://pypi.org/project/obeliks/1.0.6/
